version: '3.9'
services: 
  db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  web:
    build: .
    ports: 
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - .:/code 
    depends_on:
      - db
    env_file:
      - /.env
    
volumes:
  postgres_data:


